### ISSUE TITLE
Android studio?

### ISSUE THREAD

**Issue by borjaruiz** [Plumillon/ChipView#1]
HI, can you explain how to use this in android studio? Thanks.

**Comment by Plumillon** [comment]
Sure, my apologies I didn't write it on the readme at first.

You got 2 choices :

You can include `ChipView` in your Gradle dependencies via [JitPack](https://jitpack.io/#Plumillon/ChipView).
Example for the 1.1.0 release :
```
repositories {
        maven { url "https://jitpack.io" }
}

dependencies {
        compile 'com.github.Plumillon:ChipView:1.1.0'
}
```

Or you can download / clone it to your project and use the library folder as a library

**Comment by borjaruiz** [comment]
After doing that, I get this error:

Error:(44, 13) Failed to resolve: com.github.Plumillon:ChipView:1.1.0
<a href="openFile:/Users/Borja/Downloads/MindTheChat/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Plumillon** [comment]
Yeah I just saw there is a problem with [JitPack build](https://jitpack.io/com/github/Plumillon/ChipView/1.1.1/build.log)
I'm working on it, reopening your issue for now

**Comment by Plumillon** [comment]
Oki that's fixed with the `1.1.4` release, here the Gradle lines :
```
repositories {
        maven { url "https://jitpack.io" }
}

dependencies {
        compile 'com.github.Plumillon:ChipView:1.1.4'
}
```

**Comment by nguyenhoanglam** [comment]
I still get this error:

Error:Could not find com.github.Plumillon:ChipView:1.1.4.

**Comment by nguyenhoanglam** [comment]
Still get this error:

Error:Could not find com.github.Plumillon:ChipView:1.1.4.

**Comment by Plumillon** [comment]
I'm using it this way and all is working just fine
Please check your Gradle, do you include the lines on your build.gradle ?

JitPack is reporting the repository is fine : https://jitpack.io/#Plumillon/ChipView/1.1.4
